# Generated by Django 5.0.1 on 2024-02-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettor',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Balance'),
        ),
    ]
